const data =[
    {
        "colour":"Blue",
        "price":"2.00core",
        "img":"./assets/b1.jpg"
    },  {
        "colour":"Blue",
        "price":"2.00core",
        "img":"./assets/b2.jpg"
    },{
        "colour":"Blue",
        "price":"2.00core",
        "img":"./assets/b3.jpg"
    },{
        "colour":"Blue",
        "price":"2.00core",
        "img":"./assets/b4.jpg"
    },{
        "colour":"Blue",
        "price":"2.00core",
        "img":"./assets/b5.jpg"
    },
    
    {
        "colour":"Black",
        "price":"2.00core",
        "img":"./assets/bl1.jpg"
    },
     {
        "colour":"Black",
        "price":"2.00core",
        "img":"./assets/bl2.jpg"
    },
     {
        "colour":"Black",
        "price":"2.00core",
        "img":"./assets/bl3.jpg"
    }, {
        "colour":"Black",
        "price":"2.00core",
        "img":"./assets/bl4.jpg"
    },{
        "colour":"Black",
        "price":"2.00core",
        "img":"./assets/bl5.jpg"
    },{
        "colour":"Black",
        "price":"2.00core",
        "img":"./assets/bl6.jpg"
    },
    {
        "colour":"Red",
        "price":"2.00core",
        "img":"./assets/r1.jpg"
    },{
        "colour":"Red",
        "price":"2.00core",
        "img":"./assets/r2.jpg"
    },{
        "colour":"Red",
        "price":"2.00core",
        "img":"./assets/r3.jpg"
    },{
        "colour":"Red",
        "price":"2.00core",
        "img":"./assets/r4.jpg"
    },
]
